### ISSUE TITLE
KNX windows coverings (Slatted Blinds) big mess with new HomeKitty

### ISSUE THREAD

**Issue by Mel-Stef** [robertklep/name.klep.homekitty#24]
Dear Robert,

I move from HomeKit to HomeKitty the whole house yesterday.

Mostly of my equipment are wired KNX. Everything seems working well but slatted blinds. 

After adding slatted blinds to HomeKitty I had some very stranges behaviours:
- Activate east living room blinds and all living room are moving
- KNX relays are trigger before taking the right position (Up or DOWN)
- When using wiring KNX push button I had the same behaviour, the app is creating conflict on KNX bus also if it is not directly used
- Put on pause in Homey HomeKitty solved the issue

For now I'm using HomeKitty for all equipment but slatted blinds and HomeKit for slatted blinds and everything is working well again.

Kind regards & I wish you and your family a merry Christmas and a happy new year !

Stefano Moriggia

**Comment by robertklep** [comment]
Hi Stefano! 

Regarding this remark: "When using wiring KNX push button I had the same behaviour, the app is creating conflict on KNX bus also if it is not directly used"

Do you mean that you also have problems _outside_ of using HomeKitty?

**Comment by Mel-Stef** [comment]
Hi Robert,

Exactly I have the same mess when the command come directly from KNX push button. Because of that I was first thinking it was an hardware problem with the KNX blinds outputs relays. But stopping HomeKitty in Homey solved the issue.

**Comment by robertklep** [comment]
This might be difficult to diagnose, but we can try.

First, restart the HomeKitty app.

Then add the blinds back to HomeKit, press the button (so things go wrong), and then create a diagnostics report (in the Homey app, go to "More > Apps > HomeKitty", press the gear icon in the top right corner, and press "Create Diagnostics Report").

Once the report has been generated you can remove the blinds from HomeKit again. I should receive it automatically through e-mail.

I think I have an idea on why this happens but it might be difficult to fix.

**Comment by Mel-Stef** [comment]
I should add the blind to HomeKitty or HomeKit ? I already added back to HomeKit and there is no problem now

**Comment by robertklep** [comment]
I meant to add them to HomeKit _using_ HomeKitty.

But you can also add them directly to HomeKit _without_ HomeKitty? How does that work?

**Comment by Mel-Stef** [comment]
Sorry I mess HomeyKit and HomeKit ... No I cannot add do HomeKit without your app

**Comment by robertklep** [comment]
You sent a diagnostics report from HomeyKit, not HomeKitty 😊

If you're running HomeyKit and HomeKitty at the same time, it might be the cause for your problems.

**Comment by Mel-Stef** [comment]
Yes I'm running both at the same time and I send from HomeKitty not from HomeyKit ! (another bug ?)

**Comment by Mel-Stef** [comment]
But now is working well ! I cannot reproduce the problem

**Comment by robertklep** [comment]
I received a diagnostics report from both apps 😊

Running both at the same time may have caused the problems if both apps are trying to handle the device. So if the problems reoccur, make sure that the devices that don't work properly are disabled in one app (so the other app can handle them).

**Comment by Mel-Stef** [comment]
Yes I did that but yesterday when the problem appears HomeyKit app was deleted from Homey, only HomeKitty was installed

**Comment by robertklep** [comment]
Ah okay. So perhaps the device is now added through HomeyKit (and working) and not through HomeKitty? What is the name of the device that wasn't working properly?

**Comment by Mel-Stef** [comment]
The device is "8-Store Est Table"

I will try to delete again HomeyKit now and add one by one all blinds, testing one by one to see if the problem appears again.

I will contact you later if I can reproduce the problem.

**Comment by Mel-Stef** [comment]
Done and everything working only trough HomeKitty. For now the problem did not appears anymore

**Comment by robertklep** [comment]
Let's hope it stays that way 😊 Happy festive season! 🎄

**Comment by Mel-Stef** [comment]
I'm making some test on kNX ETS app now because HomeKit is always telling me line are "closing" and not switch to "close" also after KNX relay switch back to off and blind is closed.

This do not happen on "open"

**Comment by robertklep** [comment]
For which device (name) does that happen?

**Comment by Mel-Stef** [comment]
All slatted blind, for each I have a "status" adress coming from KNX telling the position (1 bit)
![Capture d’écran 2022-12-23 à 11 51 48](https://user-images.githubusercontent.com/113628168/209323447-28ff9056-809d-4ba0-b077-5ac5cc518571.png)

**Comment by robertklep** [comment]
This was happening in an earlier version of HomeKitty because the "target position" and the "current position" weren't in sync, but that was solved a few versions ago.

Can you find one of the devices here: https://tools.developer.homey.app/tools/devices

And then let me know the "Class" of the device and which capabilities it has (the ID and the value for each).

**Comment by Mel-Stef** [comment]
Dear Robert, 
I will post some print screen to show you with behavior I have on my slatted blinds with HomeKitty. The first problem of this topic did not appear anymore, only status when slatted blinds are down still not working in HomeKit.

**Comment by Mel-Stef** [comment]
![Blind exemple  1-Store  1 of 2](https://user-images.githubusercontent.com/113628168/209656359-ff59a2bd-498f-4051-a14d-c34fe0333374.jpeg)

**Comment by Mel-Stef** [comment]
![Blind exemple  1-Store  2 of 2](https://user-images.githubusercontent.com/113628168/209656510-003b1bb5-2742-4c4b-b9fe-9d96d0c211ef.jpeg)

**Comment by Mel-Stef** [comment]
On up position everything work well

![HomeKit view](https://user-images.githubusercontent.com/113628168/209657205-3b8e6a67-e270-4362-bb4b-9481a59484fd.jpg)

**Comment by robertklep** [comment]
And what does it show when they are in the down position?

**Comment by Mel-Stef** [comment]
![Blind exemple  1-Store  closed 1 of 2](https://user-images.githubusercontent.com/113628168/209661533-3ea56f68-9044-4533-b84d-69fe64a258ad.jpeg)

**Comment by Mel-Stef** [comment]
![Blind exemple  1-Store  closed 2 of 2](https://user-images.githubusercontent.com/113628168/209661588-0d4742be-988b-42ce-a799-93dc847e4247.jpeg)

**Comment by Mel-Stef** [comment]
![HomeKit view close](https://user-images.githubusercontent.com/113628168/209661780-812dcedf-1f89-4ddd-85b1-12efd8ed3eb5.jpg)

**Comment by Mel-Stef** [comment]
As you can see on first 2 images the status is correctly Down (after the blind completely close) but HomeKit still showing "Fermeture" (Closing)

**Comment by Mel-Stef** [comment]
The status will never be "Fermé" (Close) but it will again say correctly "Ouvert" (Open) if I open again the blind

**Comment by Mel-Stef** [comment]
this problem is on all slatted blinds (all are KNX)

**Comment by robertklep** [comment]
I don't see how it can work correctly with "open" and not with "closed" because it uses the exact same code path for that. Also, as far as I know the only reason it will show "closing..." (and also "opening...") is when the current position and target position are different, and also cannot happen because both are set at the same time to the same value (_unless_ these devices also have other capabilities besides `windowcoverings_state`, but that doesn't appear to be the case).

I also can't reproduce the problem :(

Just to be sure: you're running HomeyKit at the moment, right?

**Comment by Mel-Stef** [comment]
No HomeKitty ! with HomeyKit it was working right

**Comment by Mel-Stef** [comment]
![Blind moving up](https://user-images.githubusercontent.com/113628168/209667768-b93632b6-f6bd-4e05-bcf3-45e56fa102a3.jpeg)

**Comment by Mel-Stef** [comment]
When blind is moving up enum is set "up" and set value still "down"

**Comment by Mel-Stef** [comment]
![Blind up](https://user-images.githubusercontent.com/113628168/209668030-84422d8a-209c-455d-959d-fbc43a9a13aa.jpeg)

**Comment by Mel-Stef** [comment]
When is completely up enum still "up" and Set Value change to "up"

**Comment by OlivierZal** [comment]
@robertklep, I have no proof (yet) but my guess is that the device is "debounced" when 2 different characteristics are triggered or updated by the same capability. At least I think that some instance is destroyed but related old listeners are not. 

I'm not at home this week so I can't provide logs from my local, but will do so once back. I'll parse the code and see if I can provide you accurate lines where it could happen.

**Comment by robertklep** [comment]
> When blind is moving up enum is set "up" and set value still "down"

And what happens if you press "SET"?

**Comment by robertklep** [comment]
@OlivierZal setting different characteristics from the same capability has never proved to be an issue, HomeyKit also does that.

**Comment by OlivierZal** [comment]
Yes of course, that the issue I want to point out 😃 

The issue would be that a given characteristic is not correctly updated because related to an obsolete instance or listener.

**Comment by Mel-Stef** [comment]
If I press "Set" when the blind is coming down (enum "down") it move up again (because value still "up")

**Comment by robertklep** [comment]
@Mel-Stef the SET/UNSET button functionality is something that's offered on the Homey developer pages for convenience, but apps cannot control the values shown there. I have no idea why it would show a different value sometimes.

**Comment by robertklep** [comment]
@Mel-Stef you can try with the current test version (v1.2.9) that I just pushed? https://homey.app/a/name.klep.homekitty/test/

**Comment by Mel-Stef** [comment]
Fixed ! now is showing for very short time (less than 1s) "Closing" and after "Close".

Thank you very much for this (again) very top support !

Kind regards.

Stefano

**Comment by robertklep** [comment]
@Mel-Stef well, we now have to wait for other users for which I might have broken things 😅

**Comment by Mel-Stef** [comment]
Hope not !
