### ISSUE TITLE
Surveillance modes

### ISSUE THREAD

**Issue by Olimt-89** [robertklep/name.klep.homekitty#44]
### Type (brand/model) of device
Heimdall Security System

### Homey Model
- [x] "old" Homey (Pro)
- [ ] Homey Pro 2023

### Is it supported by HomeyKit?
- [x] Yes

### Device Classes

* _Class_: sensor

### Device Capabilities

ID: homealarm_state
Title: Alarmstatus for hjemmet 
Type: enum 
Value: armed / disarmed / partially_armed

Problem:

I recently changed from the old HomeyKit to HomeKitty, and I love the new app! It is so much easier to keep track of which devices that have been/can be integrated to Apple HomeKit (Home app).

There are 4 security modes in Apple Homekit (off, night, away, home). In the old HomeyKit app this worked as expected.
In HomeKitty app there is some misbehaviour. When I set to "night" mode nothing happens. I have to set it to "Home" for it to set the "partiall_armed" in the Heimdall app. 

I'm aware that the Heimdall app and Homey only uses three modes, and that is ok. 
But I expected that both "home" and "night" mode in Apple Home app would set the partially_armed mode for the Heimdall app like it used to in HomeyKit.

Ex: 
I have a "Good Night" scene in Apple Home app which is used daily. This turns off all lights, locks doors and sets the security system to "night". But the scene always fail, and the culprit is the security system which is not doing the correct change. I have then changed the scene so the "home" mode is chosen. The scene then works, but I want the security system to use "night" when it actually is night :)

I hope you could look into this and see if this can be changed.

**Comment by robertklep** [comment]
I tested, and it seems to work as expected for me: when I change the state on iOS to "night", it sets Homey's state to partially armed.

However, I think that the your issue might be caused by HomeKitty not differentiating between "target" and "current" state. It will always use "home" for any partially armed state, so also for "night". That's where HomeKitty and HomeyKit are different, and this might be the cause for your problems (in other words: if you switch on iOS to "night", it will turn on the partially armed state on Homey, which will then cause iOS to switch to "home" because that is the default partially armed state).

I've changed this behaviour, but am stuck on a design decision: what should happen on iOS if you switch between "disarmed" (or "armed") and "partially armed" on Homey? Should it set the state to the previous partial state ("night" or "home"), or should it always pick the same one (either "night" or "home")? I'm leaning towards the first solution, but am interested in your feedback. Hopefully I've explained the issue clearly 😅

FWIW, there's also another issue that needs to be fixed: if on iOS you change from "night" to "home", which both map to "partially armed", the state isn't changed properly on iOS. This is a more fundamental problem though 😬

**Comment by robertklep** [comment]
If you change from "Night" to "Home" (or vice versa), iOS will keep on showing "Arming..." until you switch to either "off" or "away". It should still work as expected, so probably not an issue (fixing it will require quite an extensive rewrite so I'd rather not do that).

The fix is available in the [current test version](https://homey.app/a/name.klep.homekitty/test/). You don't have to do anything other than installing that version, if you want to test it.

**Comment by Olimt-89** [comment]
I have installed the latest test version and it works, but still not 100% good.

When system is off, I change to «night» the iOS app shows no response, and then after a few seconds a notification banner shows system is set to night, but the system still shows no response where I select the mode. When closing the modefield where you select the mode in apple home app, the system reverts from no response to the right mode. Same applies if i forcequit the home app, the system shows the correct mode.

I suspect this have something to do with timing response or communication between the two apps. With HomeyKit the response was almost instant, while it takes some time in this app.

**Comment by robertklep** [comment]
This probably happens because you just restarted HomeKitty: when iOS loses connection to Homey, it will take some time before the Home app is showing the correct state. There are no delays anywhere, it happens to me all the time while I see all the updates flying by on console, so it's really an issue with iOS.

It may take some time before Home "catches up".

**Comment by Olimt-89** [comment]
Ok, thanks! As long as it actually sets the correct state in both Homekit and HomeKitty. I guess this issue now can be closed. :)
